apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server
    path: "/nfsshare/data"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
