apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
  namespace: default
spec:
  serviceName: nfs-server
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: boyroywax/nfs-server
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add:
              - SYS_ADMIN
              - SETPCAP
        volumeMounts:
        - mountPath: /nfsshare/data
          name: nfs-storage
        env:
        - name: SHARED_DIRECTORY
          value: "/nfsshare/data"
        - name: EXPORT_PATH
          value: "/nfsshare/data"
        - name: NFS_EXPORT_0
          value: "/nfsshare/data *(rw,sync,no_subtree_check,no_root_squash,insecure)"
  volumeClaimTemplates:
  - metadata:
      name: nfs-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 10Gi
