apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-nfs-test
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - name: shared-storage
      mountPath: /mnt/nfs
    env:
    - name: DEBIAN_FRONTEND
      value: "noninteractive"
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: nfs-pvc
  restartPolicy: Never
