apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    stream {
      # Twingate DNS Resolvers, some details here on DNS resolver: https://www.twingate.com/docs/linux-headless#containerized-jobs
      resolver 100.95.0.251 100.95.0.252 100.95.0.253 100.95.0.254 valid=30s;
      resolver_timeout 5s;

      upstream postgres_backend {
          zone postgres_backend_zone 64k;
          server db.example-vm.com:5432 resolve;
      }

      server {
          listen 5432;
          proxy_pass postgres_backend;
      }

      upstream mongodb_backend {
          zone mongodb_backend_zone 64k;
          server db.example-vm.com:27017 resolve;
      }

      server {
          listen 27017;
          proxy_pass mongodb_backend;
      }

      upstream redis_backend {
          zone redis_backend_zone 64k;
          server db.example-vm.com:6379 resolve;
      }

      server {
          listen 6379;
          proxy_pass redis_backend;
      }
    }
