apiVersion: v1
kind: Service
metadata:
  name: db-example-vm-com
spec:
  selector:
    app: twingate-client
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: mongodb
      port: 27017
      targetPort: 27017
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
