apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate-client
spec:
  selector:
    matchLabels:
      app: twingate-client
  template:
    metadata:
      labels:
        app: twingate-client
    spec:
      containers:
      - name: twingate-client
        image: twingate/client:latest
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            drop:
            - ALL
          privileged: true
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-device
        - mountPath: /etc/twingate/service_key.json
          name: twingate-databases-for-k8s
          subPath: k8s-key
      - name: nginx
        image: nginx:latest
        ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
          - name: mongodb
            containerPort: 27017
            protocol: TCP
          - name: redis
            containerPort: 6379
            protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: tun-device
      - name: twingate-databases-for-k8s
        secret:
          secretName: twingate-databases-for-k8s
      - name: nginx-config
        configMap:
          name: nginx-config
