apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    stream {
      resolver 100.95.0.251 100.95.0.252 100.95.0.253 100.95.0.254 valid=30s;
      resolver_timeout 5s;

      upstream postgres_backend {
          zone postgres_backend_zone 64k;
          server db.example-vm.com:5432 resolve;
      }

      server {
          listen 5432;
          proxy_pass postgres_backend;
      }

      upstream mongodb_backend {
          zone mongodb_backend_zone 64k;
          server db.example-vm.com:27017 resolve;
      }

      server {
          listen 27017;
          proxy_pass mongodb_backend;
      }

      upstream redis_backend {
          zone redis_backend_zone 64k;
          server db.example-vm.com:6379 resolve;
      }

      server {
          listen 6379;
          proxy_pass redis_backend;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate-client
spec:
  selector:
    matchLabels:
      app: twingate-client
  template:
    metadata:
      labels:
        app: twingate-client
    spec:
      containers:
      - name: twingate-client
        image: twingate/client:latest
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            drop:
            - ALL
          privileged: true
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /dev/net/tun
          name: tun-device
        - mountPath: /etc/twingate/service_key.json
          name: twingate-databases-for-k8s
          subPath: k8s-key
      - name: nginx
        image: nginx:latest
        ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
          - name: mongodb
            containerPort: 27017
            protocol: TCP
          - name: redis
            containerPort: 6379
            protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: tun-device
      - name: twingate-databases-for-k8s
        secret:
          secretName: twingate-databases-for-k8s
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: db-example-vm-com
spec:
  selector:
    app: twingate-client
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: mongodb
      port: 27017
      targetPort: 27017
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
