name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get commit SHA
        id: commit_sha
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get app name
        id: app_name
        run: |
          REPO_NAME="${{ github.repository }}" 
          echo "APP_NAME=\"${REPO_NAME##*/}\"" >> $GITHUB_ENV

      - name: Log in to github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply deployment config
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.PRODUCTION_CLUSTER }}
          IMAGE_NAME="ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}" \
          APP_NAME="${{ env.APP_NAME }}" \
          envsubst < production-k8s.yaml | kubectl apply -f -

      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.APP_NAME }}
